### ISSUE TITLE
Review Build system

### ISSUE THREAD

**Issue by fjcalzado** [Lemoncode/react-promise-tracker#10]
## Question 1
I notice that we are targeting the following in our current build system:
- `build:commonjs`: will build the consumable package in CommonJS modules format at `lib` folder.
- `build:es`: will build the consumable package in ES2015+ modules format at `es` folder.
- `build:umd`: will build the bundled package in UMD format at `dist` folder.
- `build:umd:min`: will build the minified bundled package in UMD format at `dist` folder.

However, the 2 first tasks for consumable package are doing just the same because Babel is not capturing `BABEL_ENV` definition. 

My suggestion is to update `.babelrc` like this:
```json
{
  "env": {
    "commonjs": {
      "presets": [
        ["env", {
          "useBuiltIns": false
        }],
        "react"
      ]
    },
    "es": {
      "presets": [
        ["env", {
          "useBuiltIns": false,
          "modules": false
        }],
        "react"
      ]
    }
  }
}
```
## Question 2
I read it is a good practice to publish the bundled UDM package with version number. Something like `react-promise-tracker-0.0.2.js`. This can be easily achieved if we modify `webpack.config.babel.js`:

```js
const version = JSON.stringify(process.env.npm_package_version).replace(/"/g, '');
const filename = `react-promise-tracker-${version}${NODE_ENV === 'production' ? '.min' : ''}.js`;
```

## Question 3
Also, I wonder what is the point of task 2 (`es`). I understand that we publish a version of our package with pure ES2015 module syntax, but why are we transpiling to es5 then? If it is targeted to greenfield projects with es6, does make sense to transpile to es6?

I can take care of this issue if you like.

**Comment by brauliodiez** [comment]
Go ahead with this task, all this build process refinements are really welcome

**Comment by fjcalzado** [comment]
The following changes have been done:

- Babel configuration `.babelrc` updated to support both provfiles `commonjs` and `es` through environment variable. 
- `es` profile fixed to target output in pure ES6 syntax.
- Added version number in UMD bundle file name. E.g.: `react-promise-tracker-0.0.2.js` and `react-promise-tracker-0.0.2.min.js`.
- Added proper library names for each module format under UMD output mode.
- Improve discoverability of the package (though Google, npm search, etc) by adding `package.json` social fields as: `keywords`, `homepage`, `contributors`, etc. Fields reordered based on NPM documentation.

**Comment by brauliodiez** [comment]
Merged
