### ISSUE TITLE
delay not working 

### ISSUE THREAD

**Issue by sburke56** [Lemoncode/react-promise-tracker#100]
I'm looking at the following [example](https://codesandbox.io/s/github/lemoncode/react-promise-tracker/tree/master/examples/02-example-delay) to use the delay feature. 

If I add a long delay ~20000 (20 sec) it should not show the spinner for 20 seconds correct?   The example doesn't seem to do that.  Am I missing something?

**Comment by nasdan** [comment]
Hi @sburke56, it looks like Codesandbox is not updating the browser demo after file changes.

Please, check the same example in Stackblitz [02-example-delay](https://stackblitz.com/github/Lemoncode/react-promise-tracker/tree/master/examples/02-example-delay)
