### ISSUE TITLE
Categories or groups to classify promises

### ISSUE THREAD

**Issue by fjcalzado** [Lemoncode/react-promise-tracker#11]
I have come up with an idea that wouldn't add too much complexity but could be useful in my opinion. If we manage to register promises under categories, we could make our react components to behave differently based on each category. 

Imagine the following API usage:
- Register a promise:
```js
const promiseHttp = fetch(url);
const promiseDatabase = ...
trackPromise(promiseHttp, "http");
trackPromise(promiseDatabase , "database");
```

- Wrap react component:
```js
export const ComponentWithTracking = promiseTrackerHoc(OriginalComponent, ["http", "database"]);
```

This way, `ComponentWithTracking` can respond to both promise categories showing  a different animation (network spinner or database icon blinking for example), or even just attach to only one kind of promises and ignore the rest. We can specific components to track specific promise categories. 

We can take advantage that our tinyEmitter already support different events.

**Comment by brauliodiez** [comment]
Right now we will a simple 1.0 version that will cover the basics but with quality.

Later one for a 1.1 version we will come back to this issue.

Another important topic is as well having a central point to handle errors.

**Comment by brauliodiez** [comment]
Implemented
