### ISSUE TITLE
Rename TrackHttp files to TrackPromise

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/react-promise-tracker#15]
To be done once we have the testing branch merged

**Comment by fjcalzado** [comment]
This was already done, committed and merged in #10 (commit [here](https://github.com/Lemoncode/react-promise-tracker/pull/12/commits/ccce149ed39f5cb0c1f4cd9da10542422f7b9a84)).

It is safe to close/resolve this ticket.
