### ISSUE TITLE
Improve `trackPromise` interface with options

### ISSUE THREAD

**Issue by fjcalzado** [Lemoncode/react-promise-tracker#41]
In order to ensure future backward compatibility, we should pass an `options` object as a second argument in `trackPromise` function. 

So the signature of `trackPromise` would look like this:
```
export const trackPromise = (promise, options) => {
   ...
}
```
where `options` is a plain object easily expandable with new future options. For now, it will only handle `area` property, so it would look like:

```
const options = {
  area: "my-custom-area",
}
```

**Comment by brauliodiez** [comment]
Done in V2
