### ISSUE TITLE
Symbol not defined error in IE11

### ISSUE THREAD

**Issue by ashishdawale20** [Lemoncode/react-promise-tracker#73]
I am getting below error in IE11 only. Working fine in chrome, Edge

![63401233-34fdde00-c3f4-11e9-8d97-a6a48edbbb56](https://user-images.githubusercontent.com/43884208/63416331-dbf67000-c41c-11e9-9f4e-e86cca26bbd7.png)

**Comment by brauliodiez** [comment]
Thanks for reporting, @Nasdan can you take a look at it? Maybe @ashishdawale20  needs to install a polyfill?

**Comment by nasdan** [comment]
Hi @ashishdawale20, do you have installed [core-js](https://github.com/zloirock/core-js) polyfills?
