### ISSUE TITLE
How to use this library with redux-saga?

### ISSUE THREAD

**Issue by piavgh** [Lemoncode/react-promise-tracker#74]
Hi everyone,

In redux-saga, usually we will have code like this: `yield call(getCurrentUser)`

**How to use react-promise-tracker with saga?**

I tried `trackPromise(yield call(getCurrentUser))` but it doesn't work.

Thanks.

**Comment by brauliodiez** [comment]
Hi,

If you have no parameters a possible solution could be:

```javascript
yield call(trackPromise, getCurrentUser)
```

If you need to feed parameters to getCurrentUser, you can make a wrapper

```javascript
const myTrackedCurrentUser = (...args) => trackPromise(getCurrentUser(...args));
yield call(myTrackedCurrentUser, /*function parameters*/);
```

You could make a generic wrapper

```javascript
const myGenericTrackedWrapper = (fn, ...args) => trackPromise(fn(...args));

// Any call could just call this wrapper
yield call(myGenericTrackedWrapper, fn /*, your additional params if needed*/)
```

**Comment by piavgh** [comment]
@brauliodiez : it works great!! Thank you very much.
