### ISSUE TITLE
Cancel spinner on promise cancellation

### ISSUE THREAD

**Issue by Zanoro9000** [Lemoncode/react-promise-tracker#76]
Hello,

I think a way to cancel the loader before the promise is finished (i.e. in a promise cancellation function) would be very useful to me and possibly others. I just need to be able to manually reset the promise tracker when I run my cancellation routine. My loading icon is screen blocking while its waiting and if a user enters and leaves a screen quickly, on slow API calls the screen can be frozen for a few seconds while the call finishes.

**Comment by brauliodiez** [comment]
Thanks for your feedback,

What about adding the following interface methdos:

```typescript
manuallyResetPromiseCounter();
manuallyDecrementPromiseCounter();
manuallyIncrementPromiseCounter();
```

By implementing something like that:
  - You would able to reset your promise status.
  - You would be able to tackle down other asynchronous scenarios (e.g. Axios interceptors).

But we should encourage users not to use this approach, is just for special cases like the one you mentioned.

Do you think it could be a good idea?

**Comment by Zanoro9000** [comment]
I think that would be a great idea! 
The increment is an interesting idea. Only having briefly looked at the source code would you run into an issue with manually decrementing and then the promise still 'finishing' even though it is in a cancelled state? 
Either way I think the functionality could be very useful for unique situations like cancellation of promises.

**Comment by brauliodiez** [comment]
Hello @Zanoro9000 manual end points implemented :), new versions released we will update the documentation soon
