### ISSUE TITLE
usePromiseTracker always return false

### ISSUE THREAD

**Issue by LBoullosa** [Lemoncode/react-promise-tracker#78]
Hello, I am trying implement a loading window with this piece of code.

promiseInProgress is always false so any progress were shown. trackPromise manages "configura" which relies in initialization/configurations aspectecs for the application.

```
const SuspenseR: React.FC<{ tag: string; Progress?: React.ReactNode }> = ({
		tag
		, Progress
		, children
		}) =>
	{
	const {promiseInProgress} = usePromiseTracker({ area: tag, delay: 500 });
	console.log(`promesa en progreso: ${promiseInProgress}`)
	return <>{promiseInProgress ? Progress : children}</>;
	};

export const Configurador = (props : any) =>
	{
	const id: string = "app";
	const [estaConfigurado, setEstaConfigurado] = useState(false);
	const inicializacion = React.useCallback(() =>
							{
							trackPromise(configura()
										.then(x=>
											{
											console.log(i18next);
											console.log(config);
											console.log(trazador);
											console.log(i18next.t('comun:entorno'));
											})
										, id)
							.catch(error=>
								{
								console.log(error);
								});
							}, []);
		
	React.useEffect(() => inicializacion(), []);

	return (
		<SuspenseR
			tag={id}
			Progress={<ProgressSpinner />}>
			<I18nextProvider i18n={i18next}>
						<App config={config} trazador={trazador}/>
			</I18nextProvider>
		</SuspenseR>
		)
	}
```

Any idea whats happening?

My deps
 ```
"dependencies": {
    "@allpro/react-router-pause": "^1.1.3",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.4.0",
    "@testing-library/user-event": "^7.2.1",
    "@types/jest": "^24.9.1",
    "@types/node": "^12.12.26",
    "@types/react": "^16.9.19",
    "@types/react-dom": "^16.9.5",
    "@types/react-router-dom": "^5.1.3",
    "classnames": "^2.2.6",
    "formik": "^2.1.3",
    "i18next": "^19.1.0",
    "primeicons": "^2.0.0",
    "primereact": "^3.4.0",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-i18next": "^11.3.1",
    "react-promise-tracker": "^2.0.5",
    "react-router-dom": "^5.1.2",
    "react-router-navigation-prompt": "^1.8.10",
    "react-scripts": "3.3.1",
    "react-transition-group": "^4.3.0",
    "typescript": "^3.7.5",
    "winston": "^3.2.1",
    "winston-config": "^0.5.1"
  }
```

Thanks in advance,

**Comment by brauliodiez** [comment]
Hello @LBoullosa could you provide us a codesandbox repro?

On the other hand are this ajax calls made right at the beginning of launching your app?

**Comment by brauliodiez** [comment]
Hello we have build a codesandbox with the code you provided: https://codesandbox.io/s/trusting-gates-br494

The tracker is returing false because we have a delay  of 500Ms (do not show spinner in 500Ms), if you remove it or you tune the async request to last longer it will return true.

**Comment by LBoullosa** [comment]
> 
> 
> Hello we have build a codesandbox with the code you provided: https://codesandbox.io/s/trusting-gates-br494
> 
> The tracker is returing false because we have a delay of 500Ms (do not show spinner in 500Ms), if you remove it or you tune the async request to last longer it will return true.

Hello Braulio,

Thanks about posting on codesanbox.

It seems weird, i remember tested with a 0 value, and....always false. Anyway, I will test it again within my code with your recomendations.

My promises arent ajax calls. For example, i18n initialization uses promises, so i track this initialization to only show my app when 18n init was ended.
