### ISSUE TITLE
Linking with <script /> tag

### ISSUE THREAD

**Issue by DavorJ** [Lemoncode/react-promise-tracker#80]
I have a case where I am unable to use the node.js/npm/webpack environment, and want to inject` react-promise-tracker` with the `<script />` HTML tag:

`<script src="https://unpkg.com/react-promise-tracker@2.0.6/dist/react-promise-tracker-2.0.6.min.js"></script>`

Subsequently, within a React object, I call `reactPromiseTracker.trackPromise()` on a fetch(URL)/setState() chain. All goes well.

Within the React render() function I then use `const { promiseInProgress } = reactPromiseTracker.usePromiseTracker()`. The execution of this line results in the following error:

`TypeError: Cannot read property 'useRef' of undefined`

Any ideas, or is this hackish way unsupported?

**Comment by brauliodiez** [comment]
Can you provide a codepen or sandbox reproducing the issue? This can help us a lot checking if there is something we can do, thanks

**Comment by DavorJ** [comment]
Minimal example using`<script />` tag.

### index.html

```
<html lang="en">
  <head>
    <!-- React. -->
    <script src="https://unpkg.com/react@16/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>

    <!-- JSX --->
    <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>

    <!-- React promise tracker -->
    <script src="https://unpkg.com/react-promise-tracker@2.0.6/dist/react-promise-tracker-2.0.6.min.js"></script>
  </head>

  <body>
    <h1>
      This is a static template, there is no bundler or bundling involved!
    </h1>

    <div id="root"></div>

    <script src="index.js" , type="text/babel"></script>
  </body>
</html>
```

### index.js

```
class TestObj extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      employees: []
    };
  }

  fetchEmployees = () => {
    console.log("Fetching");
    const URL = "http://dummy.restapiexample.com/api/v1/employees";
    reactPromiseTracker.trackPromise(
      fetch(URL)
        .then(r => r.json())
        .then(data => this.setState({ employees: data }))
    );
  };

  componentDidMount() {
    console.log("Mounted");
    this.fetchEmployees();
  }

  render() {
    console.log("Rendering TestObj");
    const { promiseInProgress } = reactPromiseTracker.usePromiseTracker();
    return (
      <div>
        <h1>Test promise tracker</h1>
        <ul>
          <li>A</li>
          <li>B</li>
          <li>C</li>
        </ul>
      </div>
    );
  }
}

ReactDOM.render(<TestObj />, document.getElementById("root"));

```

Code fails on `const { promiseInProgress } = reactPromiseTracker.usePromiseTracker();`


[![Edit objective-colden-x90fh](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/objective-colden-x90fh?fontsize=14&hidenavigation=1&theme=dark)

**Comment by brauliodiez** [comment]
Reviewing your example, you are using a hook on a class component, that's not supported by React, you can use the HoC version for this, how would it look like:

```diff
+ class TestObjInner extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      employees: []
    };
  }

  fetchEmployees = () => {
    console.log("Fetching");
    const URL = "http://dummy.restapiexample.com/api/v1/employees";
    reactPromiseTracker.trackPromise(
      fetch(URL)
        .then(r => r.json())
        .then(data => this.setState({ employees: data }))
    );
  };

  componentDidMount() {
    console.log("Mounted");
    this.fetchEmployees();
  }

  render() {
    console.log("Rendering TestObj");
+   const {promiseInProgress} = this.props;

    return (
      <div>
        <h1>Test promise tracker</h1>
        <ul>
          <li>A</li>
          <li>B</li>
          <li>C</li>
        </ul>
      </div>
    );
  }
}

+ var TestObj = reactPromiseTracker.promiseTrackerHoc(TestObjInner);

ReactDOM.render(<TestObj />, document.getElementById("root"));
```
Code Sand Box: https://codesandbox.io/s/condescending-northcutt-16qzo

Could you give a try? Thanks

**Comment by DavorJ** [comment]
Ok, thanks. The HOC function makes sense now to me. Can you elaborate a bit more on your statement: "you are using a hook on a class component, that's not supported by React," Is the example itself problematic?

**Comment by brauliodiez** [comment]
Hooks do not provide support for class components, check this issue from FB Team: https://github.com/facebook/react/issues/16116

The community is moving towards functional components + hooks, if you want to learn more about hooks we have created a set of step by step guided examples (learning by doing): https://github.com/Lemoncode/react-hooks-by-example

Hope this helps

**Comment by DavorJ** [comment]
Ok, I think I get it: `const { promiseInProgress } = reactPromiseTracker.usePromiseTracker();` internally makes use of hooks, and this is unsupported. That is why you made a wrapper for the class with the HOC function. Makes sense.

I understand that the community is moving toward functional components. Unfortunately, moving the existing codebase is not an option for me ;).

As a sidenote: your Code Sandbox doesn't generate any error, but it also doesn't render anything on screen. The approach of wrapping the class is clear though, and I implemented it in my own application, which resulted in `Cannot read property 'Component' of undefined`. I assume this has more to do with my hackish approach, and not so much with `react-promise-tracker`, so you can close this issue as far as I am concerned. 

Thank you for your help.

**Comment by brauliodiez** [comment]
Mmm.. About the approach you are following, I think the main issue can be that you are not transforming JSX? Not sure if you can in your project add that build step, if not you can follow the createElement way (a pain in the neck but works). Going to close this issue but feel free to buzz me if you need support on making that react work on plain vanilla js :) (my email: braulio.diez@lemoncode.net)
