### ISSUE TITLE
Hiding or Changing Elements as Well as Adding a Spinner

### ISSUE THREAD

**Issue by brian-t-allen** [Lemoncode/react-promise-tracker#85]
I have this installed and working great for adding a spinner to the page based on the promise status.

Is there a way to use this in conditional statements to change classes on other elements, show/hide other elements, etc?

In other words, in addition to adding <LoadingIndicator/> to the JSX, is there a way to access a boolean variable that represents the promise status and would be taken into account with a render()?

**Comment by brauliodiez** [comment]
Just to ensure I have understood your question, you want to be able to make something like:

```javascript
render() {
  return (<>
    {isLoading && <h1>Is Loading</h1>}
  </>)
}
```

If that's the case, yes you can:

- If you are using a function component you can achieve this using the _usePromiseTracker_ hook.

- For class components you can use the _promiseTrackerHoc_

**Comment by brian-t-allen** [comment]
Thanks. I'm still fairly new to React, so I saw that those existed but wasn't sure if they'd do what I want (or how to do it). Examples of these in the documentation would be great. 

Thanks for the reply and a great library that ended a week of banging my head against the wall...

**Comment by brauliodiez** [comment]
My advice here if you are starting: learn well how hooks work and try to stick to functional componentes, a good guide to get your hand wet on that (learning by doing, each example contains a step by step guide Readme.md): https://github.com/Lemoncode/react-hooks-by-example

Try to build what you want to make in a codesandbox and we can fork it and implement an example.
