### ISSUE TITLE
usePromiseTracker in two different components with two different areas

### ISSUE THREAD

**Issue by MartinezVillaresAdrian** [Lemoncode/react-promise-tracker#87]
Hello, I have an issue I want to ask you.

I have one component (app bar) using usePromiseTracker with one area, after that I created one page that also uses usePromiseTracker with a different area. Both areas exists and work and that moment, but at the moment I move away from the second page (remove the component), the first usePromiseTracker does not work anymore.

Do you know what can be causing this?

**Comment by brauliodiez** [comment]
Hello Adrian,

Can you try to uninstall and install the latest version of react-promise-tracker?

We fixed this bug two weeks ago, hope it works.

Thanks
  Braulio

**Comment by brauliodiez** [comment]
By the way are you using the hooks or the hoc version?

**Comment by MartinezVillaresAdrian** [comment]
Ok, I'll try to update It, I'll let you know tomorrow. Thank you very much.

Pd: Im using the hook at the moment

**Comment by MartinezVillaresAdrian** [comment]
It works like a charm now with the latest update. I'll close the issue

Thank you very much!!
